/**
 * Prisma MCP Tool
 * Introspect database schemas, generate Prisma client code, and manage migrations
 *
 * Based on prisma/prisma from the MCP ecosystem
 * Pure code generation — no external API needed
 */

export interface PrismaTool {
  name: 'prisma';
  permissions: ['read', 'execute'];
  execute: (params: PrismaParams) => Promise<PrismaResult>;
}

export interface PrismaParams {
  action: 'introspectSchema' | 'generateClient' | 'runMigration' | 'formatSchema';
  connectionString?: string;
  schema?: string;
  migrationName?: string;
}

export interface PrismaResult {
  success: boolean;
  data?: {
    schema?: string;
    clientCode?: string;
    migrationSql?: string;
    validated?: boolean;
    errors?: string[];
  };
  error?: string;
}

class PrismaAdapter {
  /**
   * Execute a Prisma action
   */
  async execute(params: PrismaParams): Promise<PrismaResult> {
    try {
      switch (params.action) {
        case 'introspectSchema':
          return await this.introspectSchema(params.connectionString || '');
        case 'generateClient':
          return await this.generateClient(params.schema || '');
        case 'runMigration':
          return await this.runMigration(params.schema || '', params.migrationName || 'migration');
        case 'formatSchema':
          return await this.formatSchema(params.schema || '');
        default:
          return { success: false, error: `Unknown action: ${params.action}` };
      }
    } catch (error: any) {
      return {
        success: false,
        error: error.message || 'Unknown error',
      };
    }
  }

  /**
   * Introspect a database connection string to produce a Prisma schema
   *
   * In production this would shell out to `prisma db pull --url <url>`.
   * Here we generate a representative schema from the connection string metadata.
   */
  async introspectSchema(connectionString: string): Promise<PrismaResult> {
    if (!connectionString) {
      return { success: false, error: 'connectionString is required' };
    }

    const url = new URL(connectionString);
    const dbType = this.detectDatabaseType(url.protocol);

    if (!dbType) {
      return { success: false, error: `Unsupported database protocol: ${url.protocol}` };
    }

    // Generate a starter schema with a placeholder User model
    const schema = this.buildIntrospectedSchema(dbType, {
      host: url.hostname,
      port: url.port || this.defaultPort(dbType),
      database: url.pathname.slice(1),
      user: url.username,
    });

    return {
      success: true,
      data: { schema },
    };
  }

  /**
   * Generate Prisma client code from a schema string
   */
  async generateClient(schema: string): Promise<PrismaResult> {
    if (!schema) {
      return { success: false, error: 'schema is required' };
    }

    const models = this.extractModels(schema);
    const clientCode = this.buildClientCode(models);

    return {
      success: true,
      data: { clientCode },
    };
  }

  /**
   * Create migration SQL from a schema diff
   *
   * In production this shells out to `prisma migrate diff`.
   * We generate a representative CREATE TABLE statement from the schema models.
   */
  async runMigration(schema: string, migrationName: string): Promise<PrismaResult> {
    if (!schema) {
      return { success: false, error: 'schema is required' };
    }

    const models = this.extractModels(schema);
    const statements: string[] = [];

    for (const model of models) {
      const columns = model.fields
        .map((f) => `  ${f.name} ${this.prismaTypeToSql(f.type)}${f.isId ? ' PRIMARY KEY' : ''}${!f.isRequired ? '' : ' NOT NULL'}${f.isUnique ? ' UNIQUE' : ''}`)
        .join(',\n');

      statements.push(
        `-- Create ${model.name} table\nCREATE TABLE IF NOT EXISTS "${model.name}" (\n${columns}\n);`
      );
    }

    const migrationSql = [
      `-- Migration: ${migrationName}`,
      `-- Generated by @aenews/mcp prisma tool`,
      '',
      ...statements,
    ].join('\n\n');

    return {
      success: true,
      data: { migrationSql },
    };
  }

  /**
   * Format and validate a Prisma schema string
   */
  async formatSchema(schema: string): Promise<PrismaResult> {
    if (!schema) {
      return { success: false, error: 'schema is required' };
    }

    const errors = this.validateSchema(schema);

    if (errors.length > 0) {
      return {
        success: false,
        data: { validated: false, errors },
        error: 'Schema validation failed',
      };
    }

    const formatted = this.formatSchemaString(schema);

    return {
      success: true,
      data: { schema: formatted, validated: true, errors: [] },
    };
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // PRIVATE HELPERS
  // ═══════════════════════════════════════════════════════════════════════════

  private detectDatabaseType(protocol: string): 'postgresql' | 'mysql' | 'sqlite' | null {
    const map: Record<string, 'postgresql' | 'mysql' | 'sqlite'> = {
      'postgresql:': 'postgresql',
      'postgres:': 'postgresql',
      'mysql:': 'mysql',
      'sqlite:': 'sqlite',
    };
    return map[protocol] || null;
  }

  private defaultPort(dbType: string): string {
    const map: Record<string, string> = { postgresql: '5432', mysql: '3306', sqlite: '' };
    return map[dbType] || '';
  }

  private buildIntrospectedSchema(
    dbType: string,
    info: { host: string; port: string; database: string; user: string }
  ): string {
    return `// This is an auto-generated Prisma schema from introspection.
// Review and adjust the models to match your actual database.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${dbType}"
  url      = "env("DATABASE_URL")"
}

model User {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

// Add more models by introspecting your actual database schema.
// Connection details: ${info.user}@${info.host}:${info.port}/${info.database}
`;
  }

  private extractModels(schema: string): Array<{
    name: string;
    fields: Array<{
      name: string;
      type: string;
      isId: boolean;
      isRequired: boolean;
      isUnique: boolean;
    }>;
  }> {
    const models: Array<{
      name: string;
      fields: Array<{ name: string; type: string; isId: boolean; isRequired: boolean; isUnique: boolean }>;
    }> = [];

    const modelRegex = /model\s+(\w+)\s*\{([^}]*)\}/g;
    let match: RegExpExecArray | null;

    while ((match = modelRegex.exec(schema)) !== null) {
      const modelName = match[1];
      const body = match[2];

      const fields: Array<{ name: string; type: string; isId: boolean; isRequired: boolean; isUnique: boolean }> = [];

      const fieldRegex = /(\w+)\s+(\w+)/g;
      let fieldMatch: RegExpExecArray | null;

      while ((fieldMatch = fieldRegex.exec(body)) !== null) {
        fields.push({
          name: fieldMatch[1],
          type: fieldMatch[2],
          isId: body.includes('@id'),
          isRequired: !body.includes('?') && fieldMatch[1] !== 'createdAt' && fieldMatch[1] !== 'updatedAt',
          isUnique: body.includes('@unique'),
        });
      }

      models.push({ name: modelName, fields });
    }

    return models;
  }

  private buildClientCode(models: Array<{ name: string; fields: Array<{ name: string; type: string }> }>): string {
    let code = `import { PrismaClient } from '@prisma/client';\n\nconst prisma = new PrismaClient();\n\n`;

    for (const model of models) {
      const typeName = model.name;
      code += `// ${typeName} CRUD helpers\n`;
      code += `export async function get${typeName}s() {\n  return prisma.${typeName[0].toLowerCase() + typeName.slice(1)}.findMany();\n}\n\n`;
      code += `export async function get${typeName}ById(id: number) {\n  return prisma.${typeName[0].toLowerCase() + typeName.slice(1)}.findUnique({ where: { id } });\n}\n\n`;
      code += `export async function create${typeName}(data: Omit<any, 'id'>) {\n  return prisma.${typeName[0].toLowerCase() + typeName.slice(1)}.create({ data });\n}\n\n`;
    }

    code += `export default prisma;\n`;
    return code;
  }

  private prismaTypeToSql(type: string): string {
    const map: Record<string, string> = {
      Int: 'INTEGER',
      String: 'TEXT',
      Boolean: 'BOOLEAN',
      DateTime: 'TIMESTAMP',
      Float: 'REAL',
      BigInt: 'BIGINT',
      Bytes: 'BLOB',
      Json: 'JSON',
    };
    return map[type] || 'TEXT';
  }

  private validateSchema(schema: string): string[] {
    const errors: string[] = [];

    if (!schema.includes('generator')) {
      errors.push('Missing generator block');
    }
    if (!schema.includes('datasource')) {
      errors.push('Missing datasource block');
    }
    if (!schema.includes('model')) {
      errors.push('No models defined');
    }
    if (!schema.includes('provider')) {
      errors.push('Datasource provider not specified');
    }

    return errors;
  }

  private formatSchemaString(schema: string): string {
    return schema
      .split('\n')
      .map((line) => line.trimEnd())
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }
}

export default PrismaAdapter;
